/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tron_math_TronMath */

#ifndef _Included_org_tron_math_TronMath
#define _Included_org_tron_math_TronMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tron_math_TronMath
 * Method:    pow
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_tron_math_TronMath_pow
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif